# Generated by Django 5.1.4 on 2025-01-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
