# Generated by Django 5.1.3 on 2025-01-07 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
    ]
