# Generated by Django 5.1.3 on 2025-01-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants',
        ),
    ]
